### ISSUE TITLE
Broken Tables in PML 2.3.0

### ISSUE THREAD

**Issue by tajmone** [pml-lang/pml-companion#75]
Something is not right with Tables' headers in PML 2.3.0.

While HTML headers generated via [`[table_data`][Table Data] are as expected, the HTML generated via normal [`[table`][Table] nodes are not: header cells in the former are correctly assigned the `pml-table-header-cell` class, whereas in the latter they are assigned the `pml-table-body-cell` class, which makes the header cells look like normal cells.

You can see this even in the documentation examples, where you'll notice that the ordinary [Table] headers are not styles in bold.

[Table Data]: https://www.pml-lang.dev/docs/reference_manual/index.html#node_table_data
[Table]: https://www.pml-lang.dev/docs/reference_manual/index.html#node_table

**Comment by pml-lang** [comment]
Yes. It's a bug that needs to be fixed.

**Comment by pml-lang** [comment]
Info:
This bug is now fixed in my local development branch.
The fix will be included in the next public version.

**Comment by pml-lang** [comment]
Fixed in version 3.0.0.
